function InitVE() {
    Ext.define("VisitingTaskDataSummaryViewEntity", {
        extend: "Ext.data.Model",
        fields: [{
            name: "ClientUserID",
            type: "int"
        }, {
            name: "CallDate",
            type: "datetime"
        }, {
            name: "ClientUserName",
            type: "string"
        }, {
            name: "ClientPositionID",
            type: "int"
        }, {
            name: "UserPositionName",
            type: "string"
        }, {
            name: "ClientStructureID",
            type: "string"
        }, {
            name: "DepartmentName",
            type: "string"
        }, {
            name: "FirstInTime",
            type: "datetime",
            dataFormat: "c"
        }, {
            name: "LastOutTime",
            type: "datetime",
            dataFormat: "c"
        }, {
            name: "WorkingHoursTotal",
            type: "string"
        }, {
            name: "WorkingHoursIndoor",
            type: "string"
        }, {
            name: "WorkingHoursJourneyTime",
            type: "string"
        }, {
            name: "WorkingHoursEfficiency",
            type: "string"
        }, {
            name: "VisitingTaskPlanCount",
            type: "int"
        }, {
            name: "VisitingTaskExecutionCount",
            type: "int"
        }, {
            name: "VisitingTaskExecutionEfficiency",
            type: "string"
        }, {
            name: "EffectiveVisit",
            type: "int"
        }, {
            name: "OrderSuccessRate",
            type: "string"
        }, {
            name: "summary",
            type: "string"
        }]
    });
}