function InitVE() {
    Ext.define("OrderViewEntity", {
        extend: "Ext.data.Model",
        fields: [{
            name: "OrdersID",
            type: "string"
        }, {
            name: "OrdersNo",
            type: "string"
        }, {
            name: "OrdersType",
            type: "int"
        }, {
            name: "OrdersTypeName",
            type: "string"
        }, {
            name: "OrdersTime",
            type: "datetime"
        }, {
            name: "StoreID",
            type: "string"
        }, {
            name: "StoreName",
            type: "string"
        }, {
            name: "Name",
            type: "string"
        }, {
            name: "OrdersAmount",
            type: "float"
        }, {
            name: "PaidAmount",
            type: "float"
        }, {
            name: "Arrearage",
            type: "float"
        }, {
            name: "StatusName",
            type: "string"
        }, {
            name: "Status",
            type: "int"
        }, {
            name: "Operater",
            type: "string"
        }, {
            name: "StockUpTime",
            type: "datetime"
        }, {
            name: "DeliveryTime",
            type: "datetime"
        }, {
            name: "ClientName",
            type: "string"
        }, {
            name: "ClientUserID",
            type: "int"
        }, {
            name: "ClientStructureID",
            type: "string"
        }, {
            name: "StockUpMan",
            type: "string"
        }, {
            name: "DeliveryMan",
            type: "string"
        }, {
            name: "Address",
            type: "string"
        }, {
            name: "ContactName",
            type: "string"
        }, {
            name: "ContactPhone",
            type: "string"
        }, {
            name: "WarehouseID",
            type: "string"
        }, {
            name: "WarehouseName",
            type: "string"
        }]
    });
}